### PR TITLE
Add some includes

### PR DESCRIPTION
**Pull request by lfranchi**
For some reason I needed this to make tomahawk build on 10.11: i just upgraded to the GM version after running betas all summer.

Not really sure why. TomahawkSettings pulls in attica.h, and all of these modules pull in TomahawkSettings. I don't understand why /usr/local/include is no longer being auto-added to my include dir path, but I suspect that's why.

Thoughts?

### CODE REVIEW

**Comment by dschmidt** [comment]
The added taglib include dirs seem rather fishy. Should be only one and then the includes should be fixed.

Adding the attica include dirs everywhere should be unneccessary, they should be "inherited" from the libtomahawk target which all of the other targets link against iirc. I'm currently busy but I can investigate, just ping me on IRC if I forget about it (I will).

P.S.: the attica issue should resolve itself the very latest when you switch to Qt5 and libattica with an ex/imported cmake target.

**Comment by lfranchi** [comment]
I agree it **should** be unnecessary, but for some reason it wasn't :)

**Comment by muesli** [comment]
Is this still relevant for you, @lfranchi? Latest git-master builds fine for me on 10.11.

**Comment by lfranchi** [comment]
Unfortunately yes, though i don't really understand why

**Comment by dschmidt** [comment]
Are you building with Qt4 or Qt5?

Try with Qt 5.5.1, should be working rather decent-ish

**Comment by lfranchi** [comment]
Using Qt 5, i'll check tonight which exact version. Not sure why that would be related though, since the includes it can't find are for other libraries not qt itself

**Comment by dschmidt** [comment]
See above.

Attica with Qt5 uses an exported cmake target, not a find module.

**Comment by muesli** [comment]
Should be obsolete with all brew recipes from homebrew-tomahawkqt5. Feel free to reopen if I'm wrong.

**Pull request closed without merging**
