### PR TITLE
Fix "control reaches end of non-void function" in DelegateConfigWrapper

### PR DESCRIPTION
**Pull request by Vogtinator**

### CODE REVIEW

**Comment by a17r** [comment]
ping, this seems like an easy fix (indendation is off but that seems fuzzy in that file already).

**Comment by dschmidt** [comment]
If you still care, I'd rather put it underneath the switch so the compiler can still warn about unhandled enum values ...

**Comment by hugolm84** [comment]
@Vogtinator Hi! I know this is a bit late, but if you do not mind, please see comments and update the PR. I will merge.

Best

**Comment by Vogtinator** [comment]
> @Vogtinator Hi! I know this is a bit late, but if you do not mind, please see comments and update the PR. I will merge.
> 
> Best

Ok, done. Thanks!

**Comment by hugolm84** [comment]
Thanks! :D

**Comment by dschmidt** [comment]
Amazing, thanks for getting this done after all <3

**Pull request merged**
