### PR TITLE
Fixed Spotify Drag-Drop

### PR DESCRIPTION
**Pull request by AshotN**
Fixed some of the Spotify drag-drop code to allow songs to be dropped into playlists. Not completely finished with everything yet!

### CODE REVIEW

**Comment by AshotN** [comment]
There is still some code to cleanup in that function, I want to fully understand some parts before I remove them or modify them.

**Comment by dschmidt** [comment]
Not finished? Do you still want this to be merged?

**Comment by AshotN** [comment]
I'm not working on it, from what I remember it works, so I think its worth cleaning up a little and merging.

**Comment by a17r** [comment]
I guess the question was if you were going to clean it up a little before it can be merged as-is. ;)

**Comment by AshotN** [comment]
I don't know if my changes still work, I don't even remember what I had to clean up. Unless someone else is willing to take it over I don't know if it's worth the bother in setting up a environment to test it

**Comment by p01arst0rm** [comment]
i can take a look over it if you'd like.

**Comment by AshotN** [comment]
You are welcome to finish off whatever I started. But this project seems to have died sadly.

**Comment by p01arst0rm** [comment]
> You are welcome to finish off whatever I started. But this project seems to have died sadly.

not if i have anything to do with it ;)

**Comment by AshotN** [comment]
I wish you luck. I would love to see the project revived. I've started working on Ampache and we have a new JSON API in the works. If you make Tomahawk work with Ampache I would love to use it.

**Comment by volffree** [comment]
tt

**Comment by volffree** [comment]
jj

**Pull request closed without merging**
