### PR TITLE
Fix build with Qt 5.11_beta3 (dropping qt5_use_modules)

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by dschmidt** [comment]
Why are you wrapping everything in if(Qt5Core_DIR)? It's not like anything can be built without QtCore...

**Comment by a17r** [comment]
The build system made me believe that Qt4 support is still a thing? If I don't wrap it like that, build with Qt4 would be broken.

**Comment by a17r** [comment]
I would be perfectly fine with the latter. There is really no point to jump through hoops for Qt4 support now.

**Comment by a17r** [comment]
Dropped the conditionals (but backupped the previous state of the branch)

**Comment by dschmidt** [comment]
Thanks!

**Pull request merged**
