### PR TITLE
Remove miniupnpc from tree and use external one

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by justin-time** [comment]
I have tried this commit on the Stable-0.8 tree, but it does not work. 

CMake is able to find libminiupnpc but the build crashes: [miniupnpc-crash.txt](https://github.com/tomahawk-player/tomahawk/files/74801/miniupnpc-crash.txt)

**Comment by muesli** [comment]
Anything blocking this, actually? Apart from distros? ;-)

**Comment by dschmidt** [comment]
Not sure it really works, need to verify, will do when back home

**Comment by a17r** [comment]
Besides a simple rebase this just needs a small fix for the mentioned build issue:
```
diff --git a/thirdparty/libportfwd/CMakeLists.txt b/thirdparty/libportfwd/CMakeLists.txt
index ca2378f79..432177c88 100644
--- a/thirdparty/libportfwd/CMakeLists.txt
+++ b/thirdparty/libportfwd/CMakeLists.txt
@@ -19,6 +19,7 @@ target_include_directories(tomahawk_portfwd
 target_link_libraries(tomahawk_portfwd
     PRIVATE
         ${LIBMINIUPNPC_LIBRARIES}
+        Qt5::Core
 )
 
 if(WIN32)
diff --git a/thirdparty/libportfwd/include/portfwd/portfwddllmacro.h b/thirdparty/libportfwd/include/portfwd/portfwddllmacro.h
index c74702b90..42ba81f4f 100644
--- a/thirdparty/libportfwd/include/portfwd/portfwddllmacro.h
+++ b/thirdparty/libportfwd/include/portfwd/portfwddllmacro.h
@@ -19,7 +19,7 @@
 #ifndef PORTFWDDLLMACRO_H
 #define PORTFWDDLLMACRO_H
 
-#include <QtCore/qglobal.h>
+#include <qglobal.h>
 
 # if defined (PORTFWDDLLEXPORT_STATIC)
 #   define PORTFWDDLLEXPORT
@@ -33,4 +33,4 @@
 #   endif
 # endif
 
-#endif
\ No newline at end of file
+#endif
```

However, the next thing would be porting to miniupnpc-2 as I don't have prior versions available in Gentoo.

**Pull request closed without merging**
