### PR TITLE
Add htmldecode function

### PR DESCRIPTION
**Pull request by theli-ua**

### CODE REVIEW

**Comment by dschmidt** [comment]
What do you need this for? This seems like a very insecure approach..looks like you can easily inject malicious script code like this

**Comment by theli-ua** [comment]
To decode html entities like &amp; , &Lt; and friends.

**Comment by dschmidt** [comment]
You could do a string replace or something

**Comment by dschmidt** [comment]
If there is no standard js function to do it

**Comment by theli-ua** [comment]
String replace is not that reliable. You need to take into account all
special characters, it could be Unicode symbol numbers, etc. Also iirc you
already have resolvers creating temporary documents from internet provided
data.

**Comment by dschmidt** [comment]
File a bug for that then. Having this as a library function makes it look as if it was safe to use this

**Comment by theli-ua** [comment]
There is no standard JS function to do this ( sorry, missed that question earlier ).
What are your security concerns with this? <script> ?
 HTML5 specifies that a <script> tag inserted via innerHTML should not execute.
Would you consider using temporary document via document.implementation.createHTMLDocument more safe?

**Comment by dschmidt** [comment]
Ah ok. I need to check back that statement, if you are right i'll merge

**Pull request merged**
