### PR TITLE
fix structure bug

### PR DESCRIPTION
**Pull request by justin-time**
This should fix TWK-1837 and TWK-1963.

### CODE REVIEW

**Comment by muesli** [comment]
Should be fixed in source code, since those .ts files are generated. Confirmation would be appreciated.

**Comment by justin-time** [comment]
No sorry, I can not confirm it. The bug still exists. 
Using tomahawk - 0.8.99+git20150410+r277+13~ubuntu14.04.1

**Comment by dschmidt** [comment]
I just looked into this. It seems it's really what it looks like on first sight: a bug in lupdate (apparently it chokes on the DpiScaler inheritance).
The good news is: I can't reproduce this broken translation file with any lupdate on my system (neither Qt4 nor Qt5). So we likely are just using an outdated lupdate on the server that runs the transifex cronjob, we'll get this fixed tonight.

**Comment by muesli** [comment]
Hm, that's odd. lupdate should behave right now - even with the old version - since I hardcoded the context. It being picked up from DpiScaler is ridiculous anyway, that's not even a QObject ;-)

Wondering if we need to update the translation on Transifex again now, which will be pulled in by the next nightly, that's actually my best guess right now. (e.g. the German translation would still contain the wrong context until the next transifex-pull)

**Comment by justin-time** [comment]
Ok, now everything is fine.

Thank you for fixing it!

**Pull request closed without merging**
